@isTest
public class DeletedClassesTest {
    @isTest
    static void testScenario1(){
        CompanyLeadsComponentController newCompanyLeadsComponentController = new CompanyLeadsComponentController();
        MassConvertLeadsController newMassConvertLeadsController = new MassConvertLeadsController();
        LeadActivityMatchedController newLeadActivityMatchedController = new LeadActivityMatchedController();
        LeadMatchingRuleUtility newLeadMatchingRuleUtility = new LeadMatchingRuleUtility();
    }
}